name: GitHub Actions Practica
on:
  push:

jobs:
  Explorando-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar evento
        run: echo "El flujo de trabajo ha sido ejecutado en el evento: ${{ github.event_name }}"
      - name: Mostrar información del servidor
        run: echo "El trabajo se está ejecutando en un servidor ${{ runner.os }} hospedado en GitHub"
      - name: Mostrar nombre de la rama y repositorio
        run: echo "El nombre de la rama es: ${{ github.ref }} y tu repositorio es: ${{ github.repository }}."
      - name: Verificar el código del repositorio
        uses: actions/checkout@v2
      - name: Confirmar verificación
        run: echo "El flujo de trabajo está listo para verificar el código en el runner."
      - name: Listar archivos en el repositorio
        run: |
          ls ${{ github.workspace }}
      - name: Mostrar estado del trabajo
        run: echo "El estado del trabajo es: ${{ job.status }}."
